In [59]:
#Import libraries
import pandas as pd
import numpy as np

In [60]:
#Read in stats data
nfl_defensive = pd.read_csv("data/nfl/stats/Career_Stats_Defensive.csv")
nfl_field_goal = pd.read_csv("data/nfl/stats/Career_Stats_Field_Goal_Kickers.csv")
nfl_fumble = pd.read_csv("data/nfl/stats/Career_Stats_Fumbles.csv")
nfl_kick_return = pd.read_csv("data/nfl/stats/Career_Stats_Kick_Return.csv")
nfl_kickoff = pd.read_csv("data/nfl/stats/Career_Stats_Kickoff.csv")
nfl_passing = pd.read_csv("data/nfl/stats/Career_Stats_Passing.csv")
nfl_punt_return = pd.read_csv("data/nfl/stats/Career_Stats_Punt_Return.csv")
nfl_punting = pd.read_csv("data/nfl/stats/Career_Stats_Punting.csv")
nfl_receiving = pd.read_csv("data/nfl/stats/Career_Stats_Receiving.csv")
nfl_rushing = pd.read_csv("data/nfl/stats/Career_Stats_Rushing.csv")

#Read in salary data
nfl_salaries = pd.read_csv("data/nfl/player_salaries/nfl_salary.csv")

In [61]:
def cleanData(data):
    data.drop(columns=['Player Id'], inplace=True)
    temp = data['Name'].str.split(',')
    data['Name'] = temp.str[1] + ' ' + temp.str[0]
    data.drop(data[data['Year'] <= 2000].index, inplace=True)
    data.sort_values('Year', inplace=True)

dataToClean = [nfl_receiving, nfl_passing, nfl_rushing, nfl_defensive, nfl_fumble, nfl_field_goal, nfl_kick_return, nfl_kickoff, nfl_punt_return, nfl_punting]

for i in dataToClean:
    cleanData(i)

In [62]:
nfl_salaries.drop(columns=['playerId', 'signingBonus', 'rosterBonus', 'workoutBonus', 'restructureBonus', 'optionBonus', 'incentive', 'salary', 'team'], inplace=True)
nfl_salaries.rename(columns={'playerName': 'Name', 'year': 'Year', 'totalCash': 'Salary'}, inplace=True)
nfl_salaries.drop(nfl_salaries[nfl_salaries['Year'] < 2000].index, inplace=True)
nfl_salaries.drop(nfl_salaries[nfl_salaries['Year'] > 2016].index, inplace=True)
nfl_salaries.sort_values('Year', inplace=True)

nfl_salaries.to_csv('data/nfl/player_salaries/nfl_salaries.csv')
nfl_salaries

                   Name  Year      Salary
1419     Adam Vinatieri  2000    $575,000
699         Phil Dawson  2000    $275,000
1796         Drew Brees  2001  $2,165,000
1420     Adam Vinatieri  2001    $650,000
700         Phil Dawson  2001    $389,000
...                 ...   ...         ...
1572       Daniel Brown  2016     $61,764
1582  Orlando Scandrick  2016  $5,000,000
1587    Sharrod Neasman  2016      $7,500
1589    Sharrod Neasman  2016    $291,170
2935     DeVante Parker  2016    $929,389

[1839 rows x 3 columns]

In [63]:
nflStats = pd.merge(nfl_passing, nfl_receiving, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats.rename(columns={'Fumbles': 'Receiving Fumbles'}, inplace=True)
nflStats = pd.merge(nflStats, nfl_rushing, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats.rename(columns={'Fumbles': 'Rushing Fumbles'}, inplace=True)
nflStats = pd.merge(nflStats, nfl_defensive, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats = pd.merge(nflStats, nfl_fumble, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats = pd.merge(nflStats, nfl_field_goal, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats = pd.merge(nflStats, nfl_kick_return, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats = pd.merge(nflStats, nfl_kickoff, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats = pd.merge(nflStats, nfl_punt_return, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')
nflStats = pd.merge(nflStats, nfl_punting, on=['Name', 'Year', 'Position', 'Team', 'Games Played'], how='outer')

nflStats.drop_duplicates(subset=['Name', 'Year'], inplace=True)
nflStats.dropna(subset=['Position'], inplace=True)
nflStats.sort_values('Year', inplace=True)

nflStats.to_csv("data/nfl/stats/nflStats.csv")
nflStats

,Name,Position,Year,Team,Games Played,Passes Attempted,Passes Completed,Completion Percentage,Pass Attempts Per Game,Passing Yards,...,Net Punting Average,Punts Blocked,Out of Bounds Punts,Downed Punts,Punts Inside 20 Yard Line,Touchbacks,Fair Catches,Punts Returned,Yards Returned on Punts,TDs Returned on Punt
38,Shane Lechler,P,2001,Oakland Raiders,16,--,--,--,0.0,--,...,35.6,1,16,6,23,12,5,34,502,0
46,Drew Brees,QB,2001,San Diego Chargers,1,27,15,55.6,27.0,221,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,Steve Smith,WR,2001,Carolina Panthers,15,--,--,--,0.0,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,Tom Brady,QB,2001,New England Patriots,15,413,264,63.9,27.5,"2,843",...,--,--,--,--,--,--,--,--,--,--
87,Adam Vinatieri,K,2001,New England Patriots,16,--,--,--,0.0,--,...,33.0,0,0,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6781,Arrelious Benn,WR,2016,Jacksonville Jaguars,15,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6780,Ben Braunecker,TE,2016,Chicago Bears,13,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6779,Davante Adams,WR,2016,Green Bay Packers,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6750,Roosevelt Nix-Jones,FB,2016,Pittsburgh Steelers,10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17280,Jacob Schum,P,2016,Green Bay Packers,16,NaN,NaN,NaN,NaN,NaN,...,39.1,0,11,7,19,4,18,16,151,0

In [64]:
nflName = nflStats['Name']
nflName = nflName.drop_duplicates()
nflName.to_csv("data/nfl/nflName.csv", index=False, header=False)
nflName

38        Shane Lechler
46           Drew Brees
56          Steve Smith
58            Tom Brady
87       Adam Vinatieri
             ...
6787        Matt Lengel
6786      Brandon Wilds
6784      Ifeanyi Momah
6783         Tyler Boyd
6780     Ben Braunecker
Name: Name, Length: 1648, dtype: object

In [65]:
nfl = pd.concat([nflStats, nfl_salaries], axis=1)
nfl.to_csv("data/nfl/nfl.csv")
nfl

,Name,Position,Year,Team,Games Played,Passes Attempted,Passes Completed,Completion Percentage,Pass Attempts Per Game,Passing Yards,...,Downed Punts,Punts Inside 20 Yard Line,Touchbacks,Fair Catches,Punts Returned,Yards Returned on Punts,TDs Returned on Punt,Name,Year,Salary
38,Shane Lechler,P,2001.0,Oakland Raiders,16.0,--,--,--,0.0,--,...,6,23,12,5,34,502,0,NaN,NaN,NaN
46,Drew Brees,QB,2001.0,San Diego Chargers,1.0,27,15,55.6,27.0,221,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clayton Geathers,2015.0,"$968,930"
56,Steve Smith,WR,2001.0,Carolina Panthers,15.0,--,--,--,0.0,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Will Compton,2014.0,"$617,014"
58,Tom Brady,QB,2001.0,New England Patriots,15.0,413,264,63.9,27.5,"2,843",...,--,--,--,--,--,--,--,Will Compton,2016.0,"$851,511"
87,Adam Vinatieri,K,2001.0,New England Patriots,16.0,--,--,--,0.0,--,...,1,1,0,0,0,0,0,Harry Douglas,2015.0,"$3,798,852"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jamaal Charles,2016.0,"$5,312,500"
1539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matt Overton,2016.0,"$800,000"
1552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preston Brown,2016.0,"$631,750"
1572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Brown,2016.0,"$61,764"
2935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DeVante Parker,2016.0,"$929,389"

In [66]:
# dataToMerge = [nfl_receiving, nfl_rushing, nfl_defensive, nfl_fumble, nfl_field_goal, nfl_kick_return, nfl_kickoff, nfl_punt_return, nfl_punting]
# nfl = nfl_passing.merge(nfl_salaries, on=['Name', 'Year'], how='outer')

# nfl.to_csv('data/nfl/nfl.csv', index=False)
# nfl

# def mergeData(data, salary):
#     data.merge(salary, on=['Name', 'Year'], how='right')

# for i in dataToMerge:
#     mergeData(i, nfl_salaries)



# nflStats = pd.merge(nfl_passing, nfl_receiving, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats.rename(columns={'Fumbles': 'Receiving Fumbles'}, inplace=True)
# nflStats = pd.merge(nflStats, nfl_rushing, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats.rename(columns={'Fumbles': 'Rushing Fumbles'}, inplace=True)
# nflStats = pd.merge(nflStats, nfl_defensive, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats = pd.merge(nflStats, nfl_fumble, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats = pd.merge(nflStats, nfl_field_goal, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats = pd.merge(nflStats, nfl_kick_return, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats = pd.merge(nflStats, nfl_kickoff, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats = pd.merge(nflStats, nfl_punt_return, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')
# nflStats = pd.merge(nflStats, nfl_punting, on=['Name', 'Year', 'Position', 'Team', 'Games Played', 'Salary'], how='outer')

# nfl.drop_duplicates(subset=['Name', 'Year'], inplace=True)
# nflStats.dropna(subset=['Position'], inplace=True)

# nflStats.to_csv("data/nfl/stats/nflStats.csv")
# nflStats